### ISSUE TITLE
component macro does not expand well

### ISSUE THREAD

**Issue by oguizol** [zambal/marker#2]
Hi,

I am trying to use marker to generate some html and it seems the generation is partial.
For instance, let say I have this component in MyTestComponent module

```
  component :form_input do
    custom_type = @type || "text" # default to text
    # div class: "form-group" do
      label @label, for: @id
      input id: @id,
            type: custom_type,
            class: "a_class",
            placeholder: @placeholder,
            name: "name",
            value: "a value"
    # end
  end
```

I use the component like this

```
  use Marker
  use Marker.HTML
  require MyTestComponent
  import MyTestComponent
```

`form_input id: "label", label: "Label", placeholder: "My component name"`

The output is missing the label element:

```
{ :safe, "<input id='label' type='text' class='pure-input-1' placeholder='My component name' name='name' value='a value'/>"}
```

If I uncomment the div element in the component definition, then I get the result:

``` :safe, <div class='form-group'><label for='label'><input id='label' type='text' class='pure-input-1' placeholder='My component name' name='name' value='a value'/>"
```

I could live with this change but I tried the same for another component:

```
  component :form_select do
    div class: "form-group" do
      label @label, for: @id
      select @__content__, id: @id, class: "a_class"
    end
  end
```

And it did not work at all:

```
form_select id: "method", label: "Method", placeholder: "GET" do
      option "GET", value: "GET"
      option "PUT", value: "PUT"
      option "POST", value: "POST"
      option "DELETE", value: "DELETE"
    end
```

output has no option at all:

```
"{ :safe, <div class='form-group'><label for='method'>Method</label><select id='method' class='a_class'></select></div>"}
```

Any idea what's wrong?
Thanks!

**Comment by zambal** [comment]
Hi,

Your first example doesn't work because the body of components are evaluated like normal functions: it returns the value of the last expression. So `label @label, for: @id` doesn't get included in the output because it's not the last expression. To make your example work you can either wrap the `label` and `intput` elements in something like a `div` element (as you tried yourself), or include them in a list and return that.

I don't know why the second example doesn't work for you. If I copy paste the code in a test module and execute it, I seem to get the expected result:

``` elixir
{:safe,
 "<div class='form-group'><label for='method'>Method</label><select id='method' class='a_class'><option value='GET'>GET</option><option value='PUT'>PUT</option><option value='POST'>POST</option><option value='DELETE'>DELETE</option></select></div>"}
```

BTW, if you import a module, you don't need to require it too, as this happens implicitly when importing too. Also, you don't need to type:

``` elixir
use Marker
```

when using a component. `use Marker` just imports the `component` macro from the Marker module and you only need that when defining new components.

**Comment by oguizol** [comment]
Thanks for the reply.
I updated the code to return a list. As a result I get a list as followed:

```
{:safe, [safe: "<label for='label'>Label</label>",
            safe: "<input id='label' type='text' class='pure-input-1' placeholder='My component name' name='name' value='a value'/>"]}
```

I added 

```
|> Marker.Compiler.compile()
```

And it worked except for the form_select component. I guess because of the @**content**  that would need to be handled as well.

Not sure it's the right way to do things... Is there a nicer way to do it?

**Comment by oguizol** [comment]
Hi Vincent,
Attached a sample project where you can experience my second issue (the real one ;-)

Thanks again!
[marker_test.zip](https://github.com/zambal/marker/files/479343/marker_test.zip)

**Comment by oguizol** [comment]
Hi Vincent,
Have you had the time to check my sample project?
Also, can you explain why putting a div block would work while for a custom component we would need to return a list (and use Marker.Compiler.compile())?

**Comment by zambal** [comment]
I can understand the difference between _using_ elements and components and _defining_ one can be confusing, but defining a component is like defining a function: it just returns the last expression. If you define a component like this:

``` elixir
component :test do
  1
  2
end
```

It will return `2` when called, just like a function. Marker components just provide some syntactic sugar for defining a function with some special rules that allow the `@` syntax inside its body and tries to compile all arguments passed to HTML. Element macros however compiles everything within its `do` block to HTML.

The reason for the difference is that the body of a component (or template) definition should be suitable for containing logic and conditionals. That would not be possible if the complete `do` block would be converted to HTML. For example:

``` elixir
div do
  res = if true, do: 1, else: 2
  res
end
```

Will result in a compile error, while it is perfectly allowed to write this inside a template or component definition.

Normally it is not a problem if a component returns a list instead of a string, because the component will almost always wrapped in a another element macro that will compile the result to a string.

For example:

``` elixir
div do
  my_component id: "test" do
    1
    2
    3
  end
end
```

will return a string.

**Comment by oguizol** [comment]
Thanks for the clarification between html element blocks and component blocks.

But this does not explain why my test sample does not work: The test uses a component and I expect the block content to be injected in the select element but running the test returns an empty select.
Weirdly, if I update your project test to the very same behaviour it's working fine.

Did you have a look at the zipped archive? Am I missing something?

**Comment by zambal** [comment]
Sorry, I did miss the test. The reason that the test fails is subtle and has to do with Elixir's parser rules regarding braces and the `do...end` syntactic sugar. If we translate the following to how elixir's parser interprets it:

``` elixir
# Original
assert {:safe, content} = form_select id: "method", label: "Method" do
      option "GET", value: "GET"
      option "PUT", value: "PUT"
      option "POST", value: "POST"
      option "DELETE", value: "DELETE"
    end

# How Elixir's parser interprets the above

assert({:safe, content} = form_select(id: "method", label: "Method"))  do
      option "GET", value: "GET"
      option "PUT", value: "PUT"
      option "POST", value: "POST"
      option "DELETE", value: "DELETE")
end
```

In other words. The parser sees the `do...end` block as the second argument of the `assert` macro. This would give a compile error if there wouldn't be an assert function or macro that accepts two arguments. But apparently (I didn't know myself), ExUnit provides an assert function that accepts two arguments and silently accepted the `do...end` block as it second argument without crashing. See http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Assertions.html#assert/2

I guess this shows one of the drawbacks of dynamic languages without compiler enforced static types, as these type of bugs are hard to detect.

To make the test pass, you could write it like this:

``` elixir
assert {:safe, content} = (form_select id: "method", label: "Method" do
      option "GET", value: "GET"
      option "PUT", value: "PUT"
      option "POST", value: "POST"
      option "DELETE", value: "DELETE"
    end)
```

Notice the extra braces around the component, so Elixir's parser understands that the `do..end` block is part of the component and not part of the `assert` call.

Another option is to just write it like this:

``` elixir
result = form_select id: "method", label: "Method" do
      option "GET", value: "GET"
      option "PUT", value: "PUT"
      option "POST", value: "POST"
      option "DELETE", value: "DELETE"
end

assert {:safe, content} = result
```

**Comment by oguizol** [comment]
Wow! Thanks for figuring it out! I had an equivalent issue in the components when I had to put each entry in a list...
Closing the issue report.
Thank you.
